local _ = {
    Human = {
        idle = {
            {
                id = "http://www.roblox.com/asset/?id=02094459294", 
                weight = 1
            }, 
            {
                id = "http://www.roblox.com/asset/?id=02094459294", 
                weight = 1
            }, 
            {
                id = "http://www.roblox.com/asset/?id=02094459294", 
                weight = 1
            }
        }, 
        walk = {
            {
                id = "rbxassetid://3193948252", 
                weight = 10
            }
        }, 
        run = {
            {
                id = "rbxassetid://03201337659", 
                weight = 10
            }
        }, 
        swim = {
            {
                id = "http://www.roblox.com/asset/?id=507784897", 
                weight = 10
            }
        }, 
        swimidle = {
            {
                id = "http://www.roblox.com/asset/?id=507785072", 
                weight = 10
            }
        }, 
        jump = {
            {
                id = "http://www.roblox.com/asset/?id=2510197830", 
                weight = 10
            }
        }, 
        fall = {
            {
                id = "http://www.roblox.com/asset/?id=507767968", 
                weight = 10
            }
        }, 
        climb = {
            {
                id = "http://www.roblox.com/asset/?id=507765644", 
                weight = 10
            }
        }, 
        sit = {
            {
                id = "http://www.roblox.com/asset/?id=507768133", 
                weight = 10
            }
        }, 
        toolnone = {
            {
                id = "http://www.roblox.com/asset/?id=507768375", 
                weight = 10
            }
        }, 
        toolslash = {
            {
                id = "http://www.roblox.com/asset/?id=522635514", 
                weight = 10
            }
        }, 
        toollunge = {
            {
                id = "http://www.roblox.com/asset/?id=522638767", 
                weight = 10
            }
        }, 
        wave = {
            {
                id = "http://www.roblox.com/asset/?id=507770239", 
                weight = 10
            }
        }, 
        point = {
            {
                id = "http://www.roblox.com/asset/?id=507770453", 
                weight = 10
            }
        }, 
        hype = {
            {
                id = "http://www.roblox.com/asset/?id=2452394685", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452394685", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452394685", 
                weight = 10
            }
        }, 
        default = {
            {
                id = "http://www.roblox.com/asset/?id=2452400423", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452400423", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452400423", 
                weight = 10
            }
        }, 
        takel = {
            {
                id = "http://www.roblox.com/asset/?id=2452660796", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452660796", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452660796", 
                weight = 10
            }
        }, 
        orange = {
            {
                id = "http://www.roblox.com/asset/?id=2452424399", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452424399", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452424399", 
                weight = 10
            }
        }, 
        bestmates = {
            {
                id = "http://www.roblox.com/asset/?id=2452670286", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452670286", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452670286", 
                weight = 10
            }
        }, 
        dab = {
            {
                id = "http://www.roblox.com/asset/?id=2452429327", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452429327", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452429327", 
                weight = 10
            }
        }, 
        wiggle = {
            {
                id = "http://www.roblox.com/asset/?id=2453298157", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453298157", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453298157", 
                weight = 10
            }
        }, 
        breakdown = {
            {
                id = "http://www.roblox.com/asset/?id=2453303634", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453303634", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453303634", 
                weight = 10
            }
        }, 
        eagle = {
            {
                id = "http://www.roblox.com/asset/?id=2453340722", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453340722", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453340722", 
                weight = 10
            }
        }, 
        laugh = {
            {
                id = "http://www.roblox.com/asset/?id=507770818", 
                weight = 10
            }
        }, 
        cheer = {
            {
                id = "http://www.roblox.com/asset/?id=507770677", 
                weight = 10
            }
        }
    }, 
    Morgan = {
        idle = {
            {
                id = "http://www.roblox.com/asset/?id=3365031631", 
                weight = 1
            }, 
            {
                id = "http://www.roblox.com/asset/?id=3365031631", 
                weight = 1
            }, 
            {
                id = "http://www.roblox.com/asset/?id=3365031631", 
                weight = 1
            }
        }, 
        walk = {
            {
                id = "rbxassetid://3193948252", 
                weight = 10
            }
        }, 
        run = {
            {
                id = "rbxassetid://03201337659", 
                weight = 10
            }
        }, 
        swim = {
            {
                id = "http://www.roblox.com/asset/?id=507784897", 
                weight = 10
            }
        }, 
        swimidle = {
            {
                id = "http://www.roblox.com/asset/?id=507785072", 
                weight = 10
            }
        }, 
        jump = {
            {
                id = "http://www.roblox.com/asset/?id=2510197830", 
                weight = 10
            }
        }, 
        fall = {
            {
                id = "http://www.roblox.com/asset/?id=507767968", 
                weight = 10
            }
        }, 
        climb = {
            {
                id = "http://www.roblox.com/asset/?id=507765644", 
                weight = 10
            }
        }, 
        sit = {
            {
                id = "http://www.roblox.com/asset/?id=507768133", 
                weight = 10
            }
        }, 
        toolnone = {
            {
                id = "http://www.roblox.com/asset/?id=507768375", 
                weight = 10
            }
        }, 
        toolslash = {
            {
                id = "http://www.roblox.com/asset/?id=522635514", 
                weight = 10
            }
        }, 
        toollunge = {
            {
                id = "http://www.roblox.com/asset/?id=522638767", 
                weight = 10
            }
        }, 
        wave = {
            {
                id = "http://www.roblox.com/asset/?id=507770239", 
                weight = 10
            }
        }, 
        point = {
            {
                id = "http://www.roblox.com/asset/?id=507770453", 
                weight = 10
            }
        }, 
        hype = {
            {
                id = "http://www.roblox.com/asset/?id=2452394685", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452394685", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452394685", 
                weight = 10
            }
        }, 
        default = {
            {
                id = "http://www.roblox.com/asset/?id=2452400423", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452400423", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452400423", 
                weight = 10
            }
        }, 
        takel = {
            {
                id = "http://www.roblox.com/asset/?id=2452660796", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452660796", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452660796", 
                weight = 10
            }
        }, 
        orange = {
            {
                id = "http://www.roblox.com/asset/?id=2452424399", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452424399", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452424399", 
                weight = 10
            }
        }, 
        bestmates = {
            {
                id = "http://www.roblox.com/asset/?id=2452670286", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452670286", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452670286", 
                weight = 10
            }
        }, 
        dab = {
            {
                id = "http://www.roblox.com/asset/?id=2452429327", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452429327", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2452429327", 
                weight = 10
            }
        }, 
        wiggle = {
            {
                id = "http://www.roblox.com/asset/?id=2453298157", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453298157", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453298157", 
                weight = 10
            }
        }, 
        breakdown = {
            {
                id = "http://www.roblox.com/asset/?id=2453303634", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453303634", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453303634", 
                weight = 10
            }
        }, 
        eagle = {
            {
                id = "http://www.roblox.com/asset/?id=2453340722", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453340722", 
                weight = 10
            }, 
            {
                id = "http://www.roblox.com/asset/?id=2453340722", 
                weight = 10
            }
        }, 
        laugh = {
            {
                id = "http://www.roblox.com/asset/?id=507770818", 
                weight = 10
            }
        }, 
        cheer = {
            {
                id = "http://www.roblox.com/asset/?id=507770677", 
                weight = 10
            }
        }
    }
};
_G.AnimationTypes = {};
require(game.ReplicatedStorage.Modules.BindToRender):AddToRender("NPCAnimations", script, 1).Event:Connect(function() --[[ Line: 203 ]] --[[ Name: renderFunction ]]
    for v1 = 1, #_G.AnimationTypes do
        if _G.AnimationTypes[v1] ~= nil then
            local v2, _ = unpack(_G.AnimationTypes[v1]);
            if v2 == nil or not v2:FindFirstChild("Humanoid") then
                table.remove(_G.AnimationTypes, v1);
            end;
        else
            table.remove(_G.AnimationTypes, v1);
        end;
    end;
end);