return {
    spit = {
        {
            id = "rbxassetid://3149657208", 
            weight = 10, 
            posterBlacklist = true
        }
    }, 
    flex = {
        {
            id = "rbxassetid://3149849903", 
            weight = 10
        }
    }, 
    yawn = {
        {
            id = "rbxassetid://3152589638", 
            weight = 10, 
            posterBlacklist = true
        }
    }, 
    sleep = {
        {
            id = "rbxassetid://3155232379", 
            weight = 10, 
            looped = true, 
            posterBlacklist = true
        }
    }, 
    laugh = {
        {
            id = "rbxassetid://3158293181", 
            weight = 10, 
            posterBlacklist = true
        }
    }
};