return {
    [1] = {
        Scale = 35, 
        Offset = CFrame.Angles(-1.5707963267948966, 0, 0)
    }, 
    [2] = {
        Scale = 35, 
        Offset = CFrame.Angles(1.5707963267948966, 0, 0)
    }, 
    [3] = {
        Scale = 35, 
        Offset = CFrame.Angles(1.5707963267948966, 0, 0)
    }, 
    [4] = {
        Scale = 40, 
        Offset = CFrame.Angles(-1.5707963267948966, 0, 0)
    }, 
    [5] = {
        Scale = 20
    }, 
    [6] = {
        Scale = 50
    }, 
    [7] = {
        Scale = 15
    }, 
    [8] = {
        Scale = 35
    }
};