return {
    ["images/Fluent/AcceptMedium/12px"] = {
        Image = "rbxassetid://11654334168", 
        ImageRectOffset = Vector2.new(), 
        ImageRectSize = Vector2.new(12, 12), 
        ResampleMode = Enum.ResamplerMode.Default
    }, 
    ["images/Fluent/ChevronDownMed/12px"] = {
        Image = "rbxassetid://11654211435", 
        ImageRectOffset = Vector2.new(), 
        ImageRectSize = Vector2.new(12, 12), 
        ResampleMode = Enum.ResamplerMode.Pixelated
    }, 
    ["images/Fluent/Dash12/12px"] = {
        Image = "rbxassetid://11654333963", 
        ImageRectOffset = Vector2.new(), 
        ImageRectSize = Vector2.new(12, 12), 
        ResampleMode = Enum.ResamplerMode.Pixelated
    }, 
    ["images/Texture/Effect/Acrylic"] = {
        Image = "rbxassetid://2510585515", 
        ImageRectOffset = Vector2.new(), 
        ImageRectSize = Vector2.new(), 
        ScaleType = Enum.ScaleType.Tile, 
        ResampleMode = Enum.ResamplerMode.Pixelated, 
        TileSize = UDim2.fromOffset(300, 300), 
        ImageTransparency = 0.97
    }
};