return {
    cough = {
        {
            id = "rbxassetid://04966366177", 
            weight = 10, 
            looped = true, 
            posterBlacklist = true
        }
    }, 
    onehand = {
        {
            id = "rbxassetid://4919094618", 
            weight = 10, 
            looped = true, 
            posterBlacklist = true
        }
    }, 
    moonwalk = {
        {
            id = "rbxassetid://04966372593", 
            weight = 10, 
            looped = true, 
            posterBlacklist = true
        }
    }, 
    float = {
        {
            id = "rbxassetid://04966345219", 
            weight = 10, 
            looped = true, 
            posterBlacklist = true
        }
    }, 
    bow = {
        {
            id = "rbxassetid://04966484498", 
            weight = 10, 
            posterBlacklist = true
        }
    }, 
    thanossnap = {
        {
            id = "rbxassetid://04966482146", 
            weight = 10, 
            soundwait = 0.6, 
            posterBlacklist = true
        }
    }
};